"""
Agent Service

Encapsulates the logic for executing AI agents.
"""

import uuid
from typing import List
from ai_core.common.logging import logger
from ai_core.common.adk import run_agent_sync, standard_retry
from ai_core.agents.chat_summarizer.agent import agent as summarizer_agent
from ai_core.agents.qa.agent import agent as qa_agent
from ai_core.agents.orchestrator.agent import agent as orchestrator_agent
from ai_core.common.models import Document

@standard_retry
def run_summarizer(chat_id: str, instruction: str = None, user_id: str = "system") -> str:
    """
    Runs the Summarizer agent for a specific chat.
    
    Args:
        chat_id: The ID of the chat to summarize.
        messages: List of messages to summarize.
        instruction: Optional user instruction (e.g., "focus on key decisions").
        user_id: The ID of the user initiating the request.
        
    Returns:
        The summary text generated by the agent.
    """
    logger.info(f"Running summarizer for chat_id={chat_id}")
    
    # Pull Approach: We do NOT fetch messages here. We let the agent do it.
    # We just provide the context and instruction.
    
    base_instruction = f"Please summarize the chat history for chat_id='{chat_id}'."
    
    if instruction:
        user_message = f"{base_instruction}\n\nUser request: {instruction}"
    else:
        user_message = base_instruction
    
    return run_agent_sync(
        agent=summarizer_agent,
        user_message=user_message,
        user_id=user_id,
        session_id=f"summarizer_{chat_id}_{uuid.uuid4()}"
    )

@standard_retry
def run_document_summarizer(chat_id: str, documents: List[Document], user_id: str = "system") -> str:
    """
    Runs the Summarizer agent to summarize documents for a specific chat.
    
    Args:
        chat_id: The ID of the chat to summarize documents for.
        documents: List of documents to summarize.
        user_id: The ID of the user initiating the request.
        
    Returns:
        The summary text generated by the agent.
    """
    logger.info(f"Running document summarizer for chat_id={chat_id}, doc_count={len(documents)}")
    
    # Format documents
    formatted_docs = []
    for doc in documents:
        formatted_docs.append(f"--- Document: {doc.filename} ---\n{doc.content}\n----------------")
    
    docs_text = "\n".join(formatted_docs)
    
    user_message = f"Please summarize the following documents for chat_id='{chat_id}':\n\n{docs_text}"
    
    return run_agent_sync(
        agent=summarizer_agent,
        user_message=user_message,
        user_id=user_id,
        session_id=f"doc_summarizer_{chat_id}_{uuid.uuid4()}"
    )

@standard_retry
def run_qa(question: str, chat_id: str = None, user_id: str = "default_user") -> str:
    """
    Runs the QA agent to answer a question.
    
    Args:
        question: The user's question.
        chat_id: Optional chat ID for context.
        user_id: The ID of the user asking the question.
        
    Returns:
        The answer text generated by the agent.
    """
    if not question or not question.strip():
        raise ValueError("Вопрос не может быть пустым")
    
    logger.info(f"Running QA for user={user_id} (chat_id={chat_id}): {question}")
    
    context_prefix = f"CONTEXT: chat_id='{chat_id}'\n" if chat_id else "CONTEXT: chat_id=None\n"
    full_question = context_prefix + "Question: " + question
    
    # Используем chat_id для session_id чтобы сохранить контекст разговора в рамках чата
    session_id = f"qa_session_{chat_id}" if chat_id else f"qa_session_{user_id}"
    
    return run_agent_sync(
        agent=qa_agent,
        user_message=full_question,
        user_id=user_id,
        session_id=session_id
    )

@standard_retry
def run_orchestrator(
    chat_id: str,
    user_id: str,
    user_message: str,
    reply_to: str = None
) -> str:
    """
    Runs the orchestrator agent for a chat message.
    """
    logger.info(f"Running orchestrator for chat_id={chat_id}, user={user_id}")
    session_id = chat_id

    # Include reply_to info if provided to help routing
    context_prefix = f"CONTEXT: chat_id='{chat_id}'"
    reply_suffix = f" [reply_to:{reply_to}]" if reply_to else ""
    enriched_message = f"{context_prefix}{reply_suffix}\nUSER: {user_message}"

    return run_agent_sync(
        agent=orchestrator_agent,
        user_message=enriched_message,
        user_id=user_id,
        session_id=session_id
    )
